name: 'integration-tests'

on:
  workflow_call:
    inputs:
      WIF_PROVIDER:
        description: 'The WIF provider.'
        required: true
        type: 'string'
      WIF_SERVICE_ACCOUNT:
        description: 'The WIF service account.'
        required: true
        type: 'string'
      PROJECT_ID:
        description: 'The integration project ID.'
        required: true
        type: 'string'
      RUNNER_LABEL:
        description: 'The runs-on runner label.'
        required: true
        type: 'string'
      RUNNER_PROJECT_ID:
        description: 'The integration runner project ID.'
        required: true
        type: 'string'
      WEBHOOK_SECRET_NAME:
        description: 'The secret manager webhook secret name.'
        required: true
        type: 'string'
      GH_APP_INSTALLATION_ID:
        description: 'The integration GitHub App installation ID.'
        required: true
        type: 'string'
      SERVICE_URL:
        description: 'The URL of the deployed service.'
        required: true
        type: 'string'

jobs:
  minty:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs:
      token: '${{ steps.mint-token.outputs.token }}'
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f' # ratchet:google-github-actions/auth@v2
        with:
          create_credentials_file: false
          export_environment_variables: false
          workload_identity_provider: '${{ vars.TOKEN_MINTER_WIF_PROVIDER }}'
          service_account: '${{ vars.TOKEN_MINTER_WIF_SERVICE_ACCOUNT }}'
          token_format: 'id_token'
          id_token_audience: '${{ vars.TOKEN_MINTER_SERVICE_AUDIENCE }}'
          id_token_include_email: true

      - name: 'Mint Token'
        id: 'mint-token'
        uses: 'abcxyz/github-token-minter/.github/actions/minty@main' # ratchet:exclude
        with:
          id_token: '${{ steps.auth.outputs.id_token }}'
          service_url: '${{ vars.TOKEN_MINTER_SERVICE_URL }}'
          requested_permissions: |-
            {
              "scope": "read-jit-runners",
              "repositories": ["${{ github.event.repository.name }}"],
              "permissions": {
                "contents": "read",
                "actions": "read"
              }
            }

  test-webhook-valid-signature:
    permissions:
      id-token: 'write'
      contents: 'read'
      actions: 'read'
    needs: ['minty']
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@a6e2e39c0a0331da29f7fd2c2a20a427e8d3ad1f' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ inputs.WIF_PROVIDER }}'
          service_account: '${{ inputs.WIF_SERVICE_ACCOUNT }}'
          token_format: 'id_token'
          id_token_audience: '${{ inputs.SERVICE_URL }}'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a' # ratchet:google-github-actions/setup-gcloud@v2
        with:
          version: '529.0.0'

      - name: 'Setup Go'
        uses: 'actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5' # ratchet:actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 'Run Webhook Tester (Valid Signature)'
        id: 'valid_signature'
        run: |-
          set -euo pipefail
          cat <<EOF > valid_payload.json
          {
            "action": "queued",
            "workflow_job": {
              "id": ${{ github.run_id }},
              "run_id": ${{ github.run_id }},
              "name": "test-job",
              "labels": ["${{ inputs.RUNNER_LABEL }}"],
              "created_at": "2024-01-01T00:00:00Z"
            },
            "organization": {
              "login": "abcxyz"
            },
            "repository": {
              "name": "github-action-dispatcher-testing"
            },
            "installation": {
              "id": ${{ inputs.GH_APP_INSTALLATION_ID }}
            }
          }
          EOF
          go run ./cmd/webhook-tester \
            --webhook-url "${{ inputs.service_url }}/webhook" \
            --secret-name "projects/${{ inputs.PROJECT_ID }}/secrets/${{ inputs.WEBHOOK_SECRET_NAME }}/versions/latest" \
            --installation-id "${{ inputs.GH_APP_INSTALLATION_ID }}" \
            --project-id "${{ inputs.RUNNER_PROJECT_ID }}" \
            --run-id "${{ github.run_id }}" \
            --id-token "${{ steps.auth.outputs.id_token }}" \
            --payload-file "valid_payload.json" \
            --verify-runner \
            --github-owner "abcxyz" \
            --github-repo "github-action-dispatcher-testing" \
            --github-token "${{ needs.minty.outputs.token }}"

  test-webhook-invalid-signature:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@a6e2e39c0a0331da29f7fd2c2a20a427e8d3ad1f' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ inputs.WIF_PROVIDER }}'
          service_account: '${{ inputs.WIF_SERVICE_ACCOUNT }}'
          token_format: 'id_token'
          id_token_audience: '${{ inputs.service_url }}'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a' # ratchet:google-github-actions/setup-gcloud@v2
        with:
          version: '529.0.0'

      - name: 'Setup Go'
        uses: 'actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5' # ratchet:actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 'Run Webhook Tester (Invalid Signature)'
        id: 'invalid_signature'
        run: |-
          set -euo pipefail
          cat <<EOF > valid_payload.json
          {
            "action": "queued",
            "workflow_job": {
              "id": ${{ github.run_id }},
              "run_id": ${{ github.run_id }},
              "name": "test-job",
              "labels": ["${{ inputs.RUNNER_LABEL }}"],
              "created_at": "2024-01-01T00:00:00Z"
            },
            "organization": {
              "login": "abcxyz"
            },
            "repository": {
              "name": "github-action-dispatcher-testing"
            },
            "installation": {
              "id": ${{ inputs.GH_APP_INSTALLATION_ID }}
            }
          }
          EOF
          go run ./cmd/webhook-tester \
            --webhook-url "${{ inputs.SERVICE_URL }}/webhook" \
            --secret-name "projects/${{ inputs.PROJECT_ID }}/secrets/${{ inputs.WEBHOOK_SECRET_NAME }}/versions/latest" \
            --installation-id "${{ inputs.GH_APP_INSTALLATION_ID }}" \
            --project-id "${{ inputs.RUNNER_PROJECT_ID }}" \
            --run-id "${{ github.run_id }}" \
            --id-token "${{ steps.auth.outputs.id_token }}" \
            --payload-file "valid_payload.json" \
            --signature "bad-signature" \
            --expect-http-status 400 \
            --expect-no-build

  test-webhook-malformed-json:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@a6e2e39c0a0331da29f7fd2c2a20a427e8d3ad1f' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ inputs.WIF_PROVIDER }}'
          service_account: '${{ inputs.WIF_SERVICE_ACCOUNT }}'
          token_format: 'id_token'
          id_token_audience: '${{ inputs.service_url }}'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a' # ratchet:google-github-actions/setup-gcloud@v2
        with:
          version: '529.0.0'

      - name: 'Setup Go'
        uses: 'actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5' # ratchet:actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 'Run Webhook Tester (Malformed JSON)'
        id: 'malformed_json'
        run: |-
          set -euo pipefail
          echo '{"foo": "bar"}' > payload.json
          go run ./cmd/webhook-tester \
            --webhook-url "${{ inputs.service_url }}/webhook" \
            --secret-name "projects/${{ inputs.PROJECT_ID }}/secrets/${{ inputs.WEBHOOK_SECRET_NAME }}/versions/latest" \
            --installation-id "${{ inputs.GH_APP_INSTALLATION_ID }}" \
            --project-id "${{ inputs.RUNNER_PROJECT_ID }}" \
            --run-id "${{ github.run_id }}" \
            --id-token "${{ steps.auth.outputs.id_token }}" \
            --payload-file "payload.json" \
            --expect-http-status 400 \
            --expect-no-build

  test-webhook-missing-field:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@a6e2e39c0a0331da29f7fd2c2a20a427e8d3ad1f' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ inputs.WIF_PROVIDER }}'
          service_account: '${{ inputs.WIF_SERVICE_ACCOUNT }}'
          token_format: 'id_token'
          id_token_audience: '${{ inputs.service_url }}'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a' # ratchet:google-github-actions/setup-gcloud@v2
        with:
          version: '529.0.0'

      - name: 'Setup Go'
        uses: 'actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5' # ratchet:actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 'Run Webhook Tester (Missing Required Field)'
        id: 'missing_field'
        run: |-
          set -euo pipefail
          echo '{"action": "queued"}' > payload.json
          go run ./cmd/webhook-tester \
            --webhook-url "${{ inputs.service_url }}/webhook" \
            --secret-name "projects/${{ inputs.PROJECT_ID }}/secrets/${{ inputs.WEBHOOK_SECRET_NAME }}/versions/latest" \
            --installation-id "${{ inputs.GH_APP_INSTALLATION_ID }}" \
            --project-id "${{ inputs.RUNNER_PROJECT_ID }}" \
            --run-id "${{ github.run_id }}" \
            --id-token "${{ steps.auth.outputs.id_token }}" \
            --payload-file "payload.json" \
            --expect-http-status 400 \
            --expect-no-build

  test-webhook-not-self-hosted:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@a6e2e39c0a0331da29f7fd2c2a20a427e8d3ad1f' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ inputs.WIF_PROVIDER }}'
          service_account: '${{ inputs.WIF_SERVICE_ACCOUNT }}'
          token_format: 'id_token'
          id_token_audience: '${{ inputs.service_url }}'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a' # ratchet:google-github-actions/setup-gcloud@v2
        with:
          version: '529.0.0'

      - name: 'Setup Go'
        uses: 'actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5' # ratchet:actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 'Run Webhook Tester (Not Self-Hosted)'
        id: 'not_self_hosted'
        run: |-
          set -euo pipefail
          echo '{"action": "queued", "workflow_job": {"labels": ["not-self-hosted"]}, "installation": {"id": ${{ inputs.GH_APP_INSTALLATION_ID }} }}' > payload.json
          go run ./cmd/webhook-tester \
            --webhook-url "${{ inputs.service_url }}/webhook" \
            --secret-name "projects/${{ inputs.PROJECT_ID }}/secrets/${{ inputs.WEBHOOK_SECRET_NAME }}/versions/latest" \
            --installation-id "${{ inputs.GH_APP_INSTALLATION_ID }}" \
            --project-id "${{ inputs.RUNNER_PROJECT_ID }}" \
            --run-id "${{ github.run_id }}" \
            --id-token "${{ steps.auth.outputs.id_token }}" \
            --payload-file "payload.json" \
            --expect-http-status 200 \
            --expect-no-build

  test-webhook-incorrect-action:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@a6e2e39c0a0331da29f7fd2c2a20a427e8d3ad1f' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ inputs.WIF_PROVIDER }}'
          service_account: '${{ inputs.WIF_SERVICE_ACCOUNT }}'
          token_format: 'id_token'
          id_token_audience: '${{ inputs.service_url }}'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a' # ratchet:google-github-actions/setup-gcloud@v2
        with:
          version: '529.0.0'

      - name: 'Setup Go'
        uses: 'actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5' # ratchet:actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 'Run Webhook Tester (Incorrect Action)'
        id: 'incorrect_action'
        run: |-
          set -euo pipefail
          echo '{"action": "unexpected-action", "workflow_job": {"labels": ["self-hosted"]}, "installation": {"id": ${{ inputs.GH_APP_INSTALLATION_ID }} }}' > payload.json
          go run ./cmd/webhook-tester \
            --webhook-url "${{ inputs.service_url }}/webhook" \
            --secret-name "projects/${{ inputs.PROJECT_ID }}/secrets/${{ inputs.WEBHOOK_SECRET_NAME }}/versions/latest" \
            --installation-id "${{ inputs.GH_APP_INSTALLATION_ID }}" \
            --project-id "${{ inputs.RUNNER_PROJECT_ID }}" \
            --run-id "${{ github.run_id }}" \
            --id-token "${{ steps.auth.outputs.id_token }}" \
            --payload-file "payload.json" \
            --expect-http-status 200 \
            --expect-no-build
